version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: ./MySQL/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: PhoneAddressData
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database-net

  dotnetapp:
    build:
      context: .
      dockerfile: ./PhoneAddressBookAPI/Dockerfile
    ports:
      - "5175:5175"
    depends_on:
      - mysql
    networks:
      - database-net

volumes:
  mysql_data:

networks:
  database-net:
    driver: bridge