version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: ./MySQL/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["/run_sql.sh", "&"]
    networks:
      - database-net

  dotnetapp:
    build:
      context: .
      dockerfile: ./PhoneAddressBookAPI/Dockerfile
    ports:
      - "5175:5175"
    depends_on:
      - mysql
    networks:
      - database-net

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./MySQL/data

networks:
  database-net:
    driver: bridge