version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: PhoneAddressData
    volumes:
      - mysql_data:/var/lib/mysql

  dotnetapp:
    build: ./PhoneAddressBookAPI
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
